### ISSUE TITLE
The single SG and multi-SGs work identically

### ISSUE THREAD

**Issue by DarioUrbina** [CatStrain/Cat_skin#11]
Does this mean that you are getting in the data recording file all of the columns with identical value? I observed identical values in all columns of the data files I was recording in the lab. I was asking in issue #6  if the files were making sense, but by mistake I only uploaded an empty file (all of the columns identical).

Tailun, this might be a coding problem, perhaps all columns are being writen with info from the same SG? Please double check this.

I also tried to stretch the whole elastic material but still all of the recordings were the same. 

Please, for this kind of Issues create an Issue, don't put them in README files, which are meant to  be explanatory only. 

___________________________________________________________________________________________
Your original comment: 
which also confused me is that except the overheating problem, the single SG and multi-SGs work identically. 
Which might means the power is not the problem for overheating. then it comes to the third:

**Comment by TailunLiu** [comment]
They should not look identical, but shey should by a certain value near 0. Now that I can't see the txt file, I can't tell if that makes sense, but from our own measurements, the columns are not identical, and they respond to us stretching the skin.

**Comment by JiaoranWang** [comment]
Oh by saying "Identical" I mean, for example SG-A1 's performance is the same while testing all of 8 stran gauges at the same time  with  testing A1 alone. 
However, it may not be appropriate to say "Identical", we still need more testing

**Comment by DarioUrbina** [comment]
I checked this with Tailun today, column- and row-wise the recorded values are different.  Still need to understand the unit of the values.
