### ISSUE TITLE
Are we really seeing in the data file the info from all the SG?

### ISSUE THREAD

**Issue by DarioUrbina** [CatStrain/Cat_skin#12]
Who is in charge of the Arduino code? 

I am asking because we need to assign the solution of this problem to someone. You brought up this issue Jiaoran. Are we really seeing in the data file the info from all the SG?

However, if I try to read them all [Strain Gauges] at the same time, I don't see it "at the same time" as we know that arduino read the output the data one by one (you can set the delay time, for now is 100 ms), which means that they are actually not read at the same time. 

I haven't try to change the output time-intervel as I remember I have test the old one(350 ohm) to have the best performances at time intervel 100 ms.

**Comment by TailunLiu** [comment]
I am in  charge of the arduino code. The reading of the strain gauges are printed one by one, and between each set of reading, there's a 100ms delay. So they are read at the same time. The 100ms dealy is between the 8th strain gauge and the first one in the next turn.

**Comment by DarioUrbina** [comment]
Thanks for the comments
