### ISSUE TITLE
First time I run MATLAB code .txt file is generated, afterwards it is not.

### ISSUE THREAD

**Issue by DarioUrbina** [CatStrain/Cat_skin#2]
First time I run MATLAB code .txt file is generated, afterwards it is not.
When I run the code for a second or third time, I get the following message. The Arduino is connected to COM3, as marked in Control Panel, still I get the following message.

Is there a way to fix this?

>> valero_receive_data_from_arduino
Error using serial/fopen (line 72)
Open failed: Port: COM3 is not available. No
ports are available.
Use INSTRFIND to determine if other instrument
objects are connected to the requested device.

Error in valero_receive_data_from_arduino (line
3)
fopen(s);

**Comment by TailunLiu** [comment]
I am not sure why this happens, but make sure you do not open the serial monitor when running the Matlab code. May be that is the reason.

**Comment by DarioUrbina** [comment]
I am not opening the serial monitor. Please go to the lab and run the MATLAB code a couple of times and see if you are getting this same problem. 
If you are please do some research to figure out the reason and how to fix it.
We need to run the code repeatedly, so this process needs to be a smooth one.  We cannot be rebooting MATLAB every time we run this, too time consuming.
