### ISSUE TITLE
Is it enough to connect the Strain Gauges to only the Arduino Power Supply?

### ISSUE THREAD

**Issue by DarioUrbina** [CatStrain/Cat_skin#5]
Please add a txt file where you explain how to power the system. I suspect that the whole system, which already has a lot of cables needs to have an external power source. I don't see any cables to do that external power connection. 
Please clarify this in a txt file.

**Comment by JiaoranWang** [comment]
It might be okay as Arduino is applying 4.95v into the circuit.

**Comment by DarioUrbina** [comment]
Ok
