### ISSUE TITLE
Does current test_8.txt file in master branch makes sense?

### ISSUE THREAD

**Issue by DarioUrbina** [CatStrain/Cat_skin#6]
I created this file with the MATLAB code: valero_receive_data_from_arduino

**Comment by JiaoranWang** [comment]
It's the latest test data we have

**Comment by TailunLiu** [comment]
I didn't see anything in that file.

**Comment by DarioUrbina** [comment]
I think I the last file I left there doesn't include the recorded data. I will try recording again and let you now what I find.
